# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: AQQBot Gradle Build (Refactor Branch)
on:
  push:
    branches:
      - refactor

jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew build shadowJar
      - name: capture build artifacts (spigot)
        uses: actions/upload-artifact@v4.6.0
        with:
          name: AQQBot for Spigot
          path: |
            bukkit/build/libs/
      - name: capture build artifacts (folia)
        uses: actions/upload-artifact@v4.6.0
        with:
          name: AQQBot for Folia
          path: |
            folia/build/libs/
      - name: capture build artifacts (velocity)
        uses: actions/upload-artifact@v4.6.0
        with:
          name: AQQBot for Velocity
          path: |
            velocity/build/libs/
